In [1]:
import os
import numpy as np
import pandas as pd

In [2]:
os.chdir('models/grid_search/')

In [21]:
result = pd.read_csv('model_results.csv')
print('Total number of models',len(result))
result.head()

Total number of models 31

,Model,Accuracy,Precision,Recall,F1 score,AUC,Image Size
0,cnn-bal-aug-D0-C1-N64,0.842949,0.810638,0.976923,0.886047,0.798291,150X150
1,cnn-bal-aug-D0-C2-N64,0.778846,0.742308,0.989744,0.848352,0.708547,150X150
2,cnn-bal-aug-D1-C2-N64,0.825321,0.787321,0.987179,0.875995,0.771368,150X150
3,cnn-bal-aug-D1-C2-N128,0.814103,0.774000,0.992308,0.869663,0.754701,150X150
4,cnn-bal-aug-D1-C3-N64,0.866987,0.840355,0.971795,0.901308,0.832051,150X150

In [22]:
# Top 3 by accuracy
result.sort_values(by=['Accuracy'], ascending=False).head(5)

,Model,Accuracy,Precision,Recall,F1 score,AUC,Image Size
6,cnn-bal-aug-D1-C4-N64,0.879808,0.849224,0.982051,0.910820,0.845726,150X150
11,cnn-bal-aug-D2-C3-N128,0.871795,0.839912,0.982051,0.905437,0.835043,150X150
4,cnn-bal-aug-D1-C3-N64,0.866987,0.840355,0.971795,0.901308,0.832051,150X150
12,cnn-bal-aug-D2-C4-N64,0.865385,0.832609,0.982051,0.901176,0.826496,150X150
10,cnn-bal-aug-D2-C3-N64,0.844551,0.804574,0.992308,0.888634,0.795299,150X150

In [23]:
# Top 3 by F1
result.sort_values(by=['F1 score'], ascending=False).head(5)

,Model,Accuracy,Precision,Recall,F1 score,AUC,Image Size
6,cnn-bal-aug-D1-C4-N64,0.879808,0.849224,0.982051,0.910820,0.845726,150X150
11,cnn-bal-aug-D2-C3-N128,0.871795,0.839912,0.982051,0.905437,0.835043,150X150
4,cnn-bal-aug-D1-C3-N64,0.866987,0.840355,0.971795,0.901308,0.832051,150X150
12,cnn-bal-aug-D2-C4-N64,0.865385,0.832609,0.982051,0.901176,0.826496,150X150
10,cnn-bal-aug-D2-C3-N64,0.844551,0.804574,0.992308,0.888634,0.795299,150X150

In [24]:
# Top 3 by AUC
result.sort_values(by=['AUC'], ascending=False).head(5)

,Model,Accuracy,Precision,Recall,F1 score,AUC,Image Size
6,cnn-bal-aug-D1-C4-N64,0.879808,0.849224,0.982051,0.910820,0.845726,150X150
11,cnn-bal-aug-D2-C3-N128,0.871795,0.839912,0.982051,0.905437,0.835043,150X150
4,cnn-bal-aug-D1-C3-N64,0.866987,0.840355,0.971795,0.901308,0.832051,150X150
12,cnn-bal-aug-D2-C4-N64,0.865385,0.832609,0.982051,0.901176,0.826496,150X150
0,cnn-bal-aug-D0-C1-N64,0.842949,0.810638,0.976923,0.886047,0.798291,150X150

Model 6 has the best AUC, accuracy, and F1 scores